# Generated by Django 5.1.15 on 2026-06-24 19:28

import django.utils.timezone
import projects.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VideoProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('original', models.FileField(upload_to=projects.models.upload_to_original)),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('duration_seconds', models.FloatField(blank=True, null=True)),
                ('width', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('song_url', models.URLField(blank=True)),
                ('song_file', models.FileField(blank=True, upload_to=projects.models.upload_to_audio)),
                ('music_volume', models.FloatField(default=0.8, help_text='Background music volume 0.0–1.0')),
                ('original_audio_volume', models.FloatField(default=0.2, help_text='Original audio volume 0.0–1.0')),
                ('aspect_ratio', models.CharField(choices=[('source', 'Keep source'), ('9:16', '9:16 (vertical / Shorts / Reels / TikTok)'), ('16:9', '16:9 (landscape / YouTube)'), ('1:1', '1:1 (square / Instagram feed)'), ('4:5', '4:5 (Instagram portrait)')], default='9:16', max_length=10)),
                ('pad_color', models.CharField(default='#000000', help_text='Background padding colour (hex)', max_length=7)),
                ('codec', models.CharField(choices=[('libx264', 'H.264 (libx264) — broadly compatible'), ('libx265', 'H.265 (libx265) — smaller files, slower'), ('libvpx-vp9', 'VP9 — web optimised')], default='libx264', max_length=20)),
                ('fps', models.IntegerField(choices=[(24, '24'), (25, '25'), (30, '30'), (50, '50'), (60, '60')], default=30)),
                ('bitrate', models.CharField(choices=[('1M', '1 Mbps (small)'), ('2M', '2 Mbps (standard)'), ('4M', '4 Mbps (high quality)'), ('8M', '8 Mbps (very high)')], default='2M', max_length=10)),
                ('max_duration', models.IntegerField(default=0, help_text='Trim to N seconds (0 = keep full duration)')),
                ('ken_burns', models.BooleanField(default=False, help_text='Slow pan/zoom (good for photo slideshows)')),
                ('output', models.FileField(blank=True, upload_to=projects.models.upload_to_output)),
                ('output_filename', models.CharField(blank=True, max_length=255)),
                ('output_size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('queued', 'Queued'), ('running', 'Running'), ('done', 'Completed'), ('failed', 'Failed')], default='draft', max_length=20)),
                ('progress', models.IntegerField(default=0, help_text='0–100')),
                ('current_stage', models.CharField(blank=True, max_length=100)),
                ('error_message', models.TextField(blank=True)),
                ('log', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
