# Generated by Django 5.1.15 on 2026-06-26 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoproject',
            name='end_seconds',
            field=models.FloatField(default=0.0, help_text='Trim end point in seconds (0 = until end of clip)'),
        ),
        migrations.AddField(
            model_name='videoproject',
            name='start_seconds',
            field=models.FloatField(default=0.0, help_text='Trim start point in seconds (0 = from beginning)'),
        ),
    ]
